[book]
authors = ["KiOZ"]
language = "vi"
multilingual = false
src = "src"
title = "Good Subs Good Anime Vietsub"

[output.html]
default-theme = "navy"
curly-quotes = true
mathjax-support = true
additional-css = ["theme/pagetoc.css", "theme/sidebyside.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/Good-Subs-Good-Anime-Vietsub/anime-subs"

[output.html.print]
enable = false

[preprocessor.theme]
pagetoc = true 
turn-off = true

[output.html.fold]
enable = false
level = 1
